apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgres
        image: postgres:14.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "kubenews#123"
          - name: POSTGRES_USER
            value: 'kubenews'
          - name: POSTGRES_DB
            value: 'DB_KUBE_NEWS'

---

apiVersion: v1
kind: Service
metadata:
  name: mypostgreservice
spec:
  selector:
    app: postgre
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenewsapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: webkubenewsapp
        image: esperancaleo/kube-news:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: DB_DATABASE
            value: "DB_KUBE_NEWS"
          - name: DB_USERNAME
            value: 'kubenews'
          - name: DB_PASSWORD
            value: 'kubenews#123'
          - name: DB_HOST
            value: 'mypostgreservice'

---

apiVersion: v1
kind: Service
metadata:
  name: servicekubenews
spec:
  selector:
    app: kubenews
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30001
  type: LoadBalancer
